sudo: required

services:
  - docker

before_install:
- docker pull jekyll/jekyll:pages

script:
- docker run --rm --volume=$(pwd):/srv/jekyll -it jekyll/jekyll:pages jekyll build --drafts

notifications:
  email:
    recipients:
      - blog@barreverte.fr
    on_success: change
    on_failure: always
