language: ruby
rvm:
 - "2.2.3"
install: gem install jekyll --version 2.4
script: jekyll build
#notifications:
#  email:
#    recipients:
#      - blog@barreverte.fr
#    on_success: always
#    on_failure: always
