rkdown: maruku
pygments: true
rdiscount:
  extensions: [smart, autolink]

comments :
   provider: disqus
   disqus:
     short_name:  barreverte

name: Barre Verte !
description: Notes de développeurs sur le logiciel, le design, l'agilité, l'open source, les mobiles, linux...
url: http://www.barreverte.fr/
