# Jekyll configuration
name: Barre Verte !
description: Notes de développeurs sur le logiciel, le design, l'agilité, l'open source, les mobiles, linux...

timezone: Europe/Paris

# url is currently only used only for the RSS feed in feed.xml
url: http://www.barreverte.fr

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
#baseurl: /

# This can be '' to hide the Github nav button
github: 'barreverte/barreverte.github.io'

# enable analytics
analytics: true

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: 'barreverte'
comments: true

#permalink: /:year/:month/:title
permalink: /:title
paginate: 9

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

exclude: ['README.md', 'LICENSE', '*.sh']
encoding: utf-8
